-- THIS IS JUST A TENANTIVE SCHEMA, AUTO GENERATED BY http://ondras.zarovi.cz/sql/demo/



-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'offensive_stat'
-- 
-- ---

DROP TABLE IF EXISTS `offensive_stat`;
		
CREATE TABLE `offensive_stat` (
  `offensive_stat_id` TINYINT NULL AUTO_INCREMENT DEFAULT NULL,
  `game_id` TINYINT NULL DEFAULT NULL,
  `player_id` TINYINT NULL DEFAULT NULL,
  `team_id` TINYINT NULL DEFAULT NULL,
  `score_type_ref_id` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`offensive_stat_id`, `game_id`, `player_id`, `team_id`, `score_type_ref_id`)
);

-- ---
-- Table 'team'
-- 
-- ---

DROP TABLE IF EXISTS `team`;
		
CREATE TABLE `team` (
  `team_id` TINYINT NULL AUTO_INCREMENT DEFAULT NULL,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`team_id`)
);

-- ---
-- Table 'player'
-- 
-- ---

DROP TABLE IF EXISTS `player`;
		
CREATE TABLE `player` (
  `player_id` INT NOT NULL AUTO_INCREMENT DEFAULT NULL,
  `player_name` MEDIUMTEXT NOT NULL DEFAULT 'NULL',
  `team_id` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`player_id`, `team_id`)
);

-- ---
-- Table 'game'
-- 
-- ---

DROP TABLE IF EXISTS `game`;
		
CREATE TABLE `game` (
  `game_id` TINYINT NULL AUTO_INCREMENT DEFAULT NULL,
  `team_1_id` TINYINT NULL DEFAULT NULL,
  `team_2_id` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`game_id`, `team_1_id`, `team_2_id`)
);

-- ---
-- Table 'score_type_ref'
-- 
-- ---

DROP TABLE IF EXISTS `score_type_ref`;
		
CREATE TABLE `score_type_ref` (
  `score_type_ref_id` INT NOT NULL AUTO_INCREMENT DEFAULT NULL,
  `score_type` MEDIUMTEXT NULL DEFAULT NULL,
  `point_value` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`score_type_ref_id`)
);

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE `team` ADD FOREIGN KEY (team_id) REFERENCES `player` (`team_id`);
ALTER TABLE `team` ADD FOREIGN KEY (team_id) REFERENCES `game` (`team_1_id`);
ALTER TABLE `team` ADD FOREIGN KEY (team_id) REFERENCES `offensive_stat` (`team_id`);
ALTER TABLE `player` ADD FOREIGN KEY (player_id) REFERENCES `offensive_stat` (`player_id`);
ALTER TABLE `game` ADD FOREIGN KEY (game_id) REFERENCES `offensive_stat` (`game_id`);
ALTER TABLE `score_type_ref` ADD FOREIGN KEY (score_type_ref_id) REFERENCES `offensive_stat` (`score_type_ref_id`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `offensive_stat` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `team` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `player` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `game` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `score_type_ref` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `offensive_stat` (`offensive_stat_id`,`game_id`,`player_id`,`team_id`,`score_type_ref_id`) VALUES
-- ('','','','','');
-- INSERT INTO `team` (`team_id`,`name`) VALUES
-- ('','');
-- INSERT INTO `player` (`player_id`,`player_name`,`team_id`) VALUES
-- ('','','');
-- INSERT INTO `game` (`game_id`,`team_1_id`,`team_2_id`) VALUES
-- ('','','');
-- INSERT INTO `score_type_ref` (`score_type_ref_id`,`score_type`,`point_value`) VALUES
-- ('','','');

